site_name: Peeyush Rao – Technical Notes
theme:
  name: material

nav:
  - Home: index.md
  - EDR:
      - What is EDR?: edr/what-is-edr.md
      - DLL Sideloading: edr/dll-sideloading.md
  - Zscaler:
      - Zscaler Architecture: zscaler/zscaler-architecture.md
  - Linux:
      - Linux Basics: linux/linux-basics.md
  - Windows:
      - Windows Internals: windows/windows-internals.md
